### ISSUE TITLE
[Picture] Image "settings buttons" are situated wrongly in settings window

### ISSUE THREAD

**Issue by SydorenkoSergiy** [django-cms/djangocms-bootstrap4#10]
Steps to reproduce:
Added image plugin
Upload an image
Observe "settings buttons"

Actual result:
The buttons are overlay the text below
<img width="1068" alt="screen" src="https://user-images.githubusercontent.com/17780682/31814828-7753df00-b593-11e7-8eba-660c3bc1974e.png">

Expected result:
The buttons do not overlay the text below

**Comment by vxsx** [comment]
ready to test

**Comment by FinalAngel** [comment]
fixed
