### ISSUE TITLE
Django Carousel Plugin is not Sliding Images as it should be

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [django-cms/djangocms-bootstrap4#102]
Unable to slide the images in the djangocms-bootstrap4 plugin "carousel". Images are stacked one-by-one. Not moving at all.

**Comment by FinalAngel** [comment]
@shankarThiyagaraajan are you adding/loading the bootstrap css and javascript files in your frontend?

**Comment by shankarThiyagaraajan** [comment]
@FinalAngel, No I'm not adding anything externally. Only going with plugin scripts/styles.

FYI,
![image](https://user-images.githubusercontent.com/10199091/73165193-5b4d4580-4119-11ea-9565-051fd538e7ea.png)

**Comment by FinalAngel** [comment]
@shankarThiyagaraajan you need to add the styles and javascript from bootstrap. djangocms-bootstrap does not add that for you.

**Comment by shankarThiyagaraajan** [comment]
@FinalAngel FYI
Thanks, It's Working.

**Comment by FinalAngel** [comment]
You're welcome 👍

**Comment by garrett928** [comment]
@FinalAngel @shankarThiyagaraajan Where do you add the styles and JS to? I have download the stock bootsrap4 css and js files. I added them to static/djangocms_bootsrap4 under their respective folders. But it does not work
