### ISSUE TITLE
Exception when inserting new card under a tab item

### ISSUE THREAD

**Issue by ebugge** [django-cms/djangocms-bootstrap4#104]
I have a "Tabs" containing two "Tab items". Beneath one of the tab items, there are five "Cards". When I insert a new Card below the existing ones, I get the following exception:

> Exception while resolving variable 'disabled_child' in template 'cms/toolbar/dragitem.html'.
> Traceback (most recent call last):
> File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
>     current = current[bit]
> File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/template/context.py", line 83, in __getitem__
>     raise KeyError(key)
> KeyError: 'disabled_child'
> **NO MATCH**
> During handling of the above exception, another exception occurred:
> **NO MATCH**
> Traceback (most recent call last):
>   File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/template/base.py", line 835, in _resolve_lookup
>     if isinstance(current, BaseContext) and getattr(type(current), bit):
> AttributeError: type object 'Context' has no attribute 'disabled_child'
> **NO MATCH**
> During handling of the above exception, another exception occurred:
> **NO MATCH**
> Traceback (most recent call last):
>   File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/template/base.py", line 843, in _resolve_lookup
>     current = current[int(bit)]
> ValueError: invalid literal for int() with base 10: 'disabled_child'
> **NO MATCH**
> During handling of the above exception, another exception occurred:
> **NO MATCH**
> Traceback (most recent call last):
>   File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/template/base.py", line 850, in _resolve_lookup
>     (bit, current))  # missing attribute
> django.template.base.VariableDoesNotExist: Failed lookup for key [disabled_child] in [{'False': False, 'True': True, 'None': None}, {'plugin': <djangocms_bootstrap4.contrib.bootstrap4_tabs.models.Bootstrap4TabItem id=1737 plugin_type='Bootstrap4TabItemPlugin' object at 0x7f7dae357940>, 'cms_toolbar': <cms.toolbar.toolbar.CMSToolbar object at 0x7f7dae488198>, 'clipboard': False, 'request': <WSGIRequest: POST '/da/admin/cms/page/add-plugin/?placeholder_id=20&plugin_type=Bootstrap4CardPlugin&cms_path=/da/kontakt/?edit&plugin_language=da&plugin_parent=1737'>}, {'allow_children': True, 'disable_child_plugins': False}]

**Comment by FinalAngel** [comment]
I'm not able to reproduce this issue:

![image](https://user-images.githubusercontent.com/270307/91446149-58652f80-e877-11ea-9e02-b8b43e41574a.png)

it seems like something else is going on. Are you able to reproduce the issue consistently and can let us know how to do so?
