### ISSUE TITLE
image alignment is ignored

### ISSUE THREAD

**Issue by macolo** [django-cms/djangocms-bootstrap4#105]
This is because https://github.com/divio/djangocms-bootstrap4/blob/master/djangocms_bootstrap4/contrib/bootstrap4_picture/cms_plugins.py#L38 overrides https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/cms_plugins.py#L62

Downstream issue (closed): https://github.com/divio/djangocms-picture/issues/92

**Comment by macolo** [comment]
I noticed that this is due to a template customization where a `class` tag is hardcoded for the image, however instance.attributes_str sets the `class` tag as well which leads to duplicate `class` tag. Chrome (or the django CMS javascript logic) then removes the 2nd `class` tag.

**Comment by diwash007** [comment]
@macolo  How to get around this issue?
