### ISSUE TITLE
Distorted layout when editing Column 

### ISSUE THREAD

**Issue by SydorenkoSergiy** [django-cms/djangocms-bootstrap4#106]
**Steps to reproduce:**

1. Add Row add-on to the page
2. Edit the Column
3. Check the `Responsive settings` area

**Actual result:**
The first input-fields are not on the same line as others

**Expected result:**
All input-fields are on the same line

**Add-on version:**
1.5.0

**Screenshot:**
<img width="848" alt="Снимок экрана 2020-03-23 в 13 38 46" src="https://user-images.githubusercontent.com/17780682/77313053-d5f6a380-6d0b-11ea-9228-8d774021e9ca.png">

**Comment by FinalAngel** [comment]
Will be fixed in the new release :)

**Comment by FinalAngel** [comment]
The following issue remains after the release though:

![image](https://user-images.githubusercontent.com/270307/79873122-f6874b80-83e6-11ea-8ccb-bdec7a32d775.png)
