### ISSUE TITLE
Every second element in plugins' settings window in pushed a bit right

### ISSUE THREAD

**Issue by SydorenkoSergiy** [django-cms/djangocms-bootstrap4#11]
Steps to reproduce:
Add any plugin to page
Observe its setting window

Actual result:
Every second element in plugins' settings window in pushed a bit right

Expected result:
All element are aligned on the same line

<img width="1007" alt="screen2" src="https://user-images.githubusercontent.com/17780682/31815196-a8ce86c4-b594-11e7-9364-0426275df924.png">
<img width="610" alt="screen3" src="https://user-images.githubusercontent.com/17780682/31815197-a8ecbda6-b594-11e7-8bd9-0cb0829a3563.png">

**Comment by vxsx** [comment]
ready to test

**Comment by FinalAngel** [comment]
fixed
