### ISSUE TITLE
Unable to upload multiple files at once for bootstrap image plugin

### ISSUE THREAD

**Issue by pupattan** [django-cms/djangocms-bootstrap4#110]
Unable to upload multiple files at once showing following error
![image](https://user-images.githubusercontent.com/19246595/79965912-467b1680-84aa-11ea-9870-5caf2d723790.png)

**Comment by FinalAngel** [comment]
@pupattan do you have additional information about what versions you are using of djangocms-bootstrap4, the cms, filer and django? Is the issue still valid as I can't reproduce it with the latest versions.
