### ISSUE TITLE
Add alignment config to Columns for different breaking points

### ISSUE THREAD

**Issue by viktor-yunenko** [django-cms/djangocms-bootstrap4#113]
I have a custom plugin for alignment, but having it on the column could be simpler:

![image](https://user-images.githubusercontent.com/36416236/84508143-88fee980-acca-11ea-915c-06f263cc1719.png)

**Comment by FinalAngel** [comment]
@victor-yunenko is that still something you plan on implementing?

**Comment by viktor-yunenko** [comment]
In short yes, but probably it would be an almost complete rewrite of the bs4 plugins, since in the future I would like to greatly improve UX by avoiding bootstrap terminology.

Maybe we could even name djangocms-bootstrap5 :)

**Comment by FinalAngel** [comment]
:D
