### ISSUE TITLE
Validation error message pushes element right when leaving mandatory field empty

### ISSUE THREAD

**Issue by SydorenkoSergiy** [django-cms/djangocms-bootstrap4#12]
Steps to reproduce:
Add any plugin with has mandatory fields (e.g. badge)
Leave the mandatory field empty
Hit save

Actual result:
Validation error message pushes element right
<img width="1002" alt="screen4" src="https://user-images.githubusercontent.com/17780682/31815706-293a4626-b596-11e7-8878-fa2f634a1b75.png">

Expected result:
Validation error message is show above the mandatory field

**Comment by vxsx** [comment]
ready to test

**Comment by FinalAngel** [comment]
fixed
