### ISSUE TITLE
Please return possibility to add additional classes for bootstrap4 components

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [django-cms/djangocms-bootstrap4#120]
booststrap4 grid container component useless because does not support extra classes for example it is absolutely not possible to set padding or margin for container and  in same time it support useless attributes which almost never needed for this component.

Update: 
Same with row and column component. 

Quite often exist needle to use something like this <div class="col py-3 px-lg-5 border bg-light"> current component forcing to create weird constructions which increase complexity in admin interface and also i think not good for rendering speed

Update2: 
Same with image component. And if in case container it was possible to workaround it with standard Style components . Image is not possible to workaround

**Comment by FinalAngel** [comment]
You can do this by adding custom attributes which are present by almost any plugin:

![2020-09-23 08 35 48](https://user-images.githubusercontent.com/270307/93975639-092bf500-fd78-11ea-87ff-47cca6846cb0.gif)
