### ISSUE TITLE
Djangocms-bootstrap4 option not showing up.

### ISSUE THREAD

**Issue by steynkalala** [django-cms/djangocms-bootstrap4#122]
Please help me.
Im not getting the option of adding a djangocms-boottrap4 plugin, does any one have any idea of why not? Ill attach an image. 
![Screen Shot 2020-09-22 at 5 49 14 PM](https://user-images.githubusercontent.com/10123821/93941338-3c30a300-fcfc-11ea-8c10-f777a1bcfc31.png)

**Comment by FinalAngel** [comment]
Did you add all packages as stated in the ``README`` to your installed apps? Otherwise, we need some more information about your project setup.
