### ISSUE TITLE
[Alert] When "alert" type is span - it's cut in two lines 

### ISSUE THREAD

**Issue by SydorenkoSergiy** [django-cms/djangocms-bootstrap4#13]
Steps to reproduce:
Add "Alert" plugin to page
Open "Advanced settings"
Select "tag type" as span
Hit save
Add "Text" plugin to "Alert" plugin
Observe the plugin in FE

Actual result:
The alert looks cut in two lines
<img width="597" alt="screen5" src="https://user-images.githubusercontent.com/17780682/31817136-7694fcea-b59b-11e7-955f-1f4db99835c5.png">

Expected result:
The alert remains in one line

**Comment by FinalAngel** [comment]
Will remove the span alltogether
