### ISSUE TITLE
Error when doing pip install

### ISSUE THREAD

**Issue by trsh** [django-cms/djangocms-bootstrap4#19]
Could not find a version that satisfies the requirement djangocms-bootstrap4 (from versions: )
No matching distribution found for djangocms-bootstrap4

All requirements are satisfied. Checked on by one.

**Comment by FinalAngel** [comment]
hello @trsh this is not yet available on pip as we are still working on it. Be careful cause it's still alpha ;)

**Comment by trsh** [comment]
@FinalAngel consider adding this info to docs
