### ISSUE TITLE
Feature Request: Add Background Color or Image to containers

### ISSUE THREAD

**Issue by oesah** [django-cms/djangocms-bootstrap4#32]
Hi!

First of all, thanks for this plugin. I am using it in one of my Django CMS projects and have been using the BS3 Version in other projects.

I would like to ask for a feature, if it doesn't exist yet: 

If a user creates a container plugin instance, he should be able to set a background via CSS or other form. It can be a color, gradient, custom CSS, or a FilerImage. In general, one thing that could be improved with this plugin is a bite more flexibility when it comes to styling. Some modules already have an additional class variable. It would be nice if all could have that, containers, rows, etc.

Regards, Özer

**Comment by vxsx** [comment]
I believe you can add a class or style via an [attribute field](https://github.com/divio/djangocms-attributes-field) for almost every plugin.

As for the image background - if you want to use filer image you are better off using a custom template of djangocms-picture instead. I.e. it should be an image plugin, not container plugin

**Comment by FinalAngel** [comment]
Thanks @vxsx also to visualise:
![2018-03-19 08 39 25](https://user-images.githubusercontent.com/270307/37583294-23a009d6-2b51-11e8-9228-afa274d849e4.gif)

For background image there is also aldryn-background-image: https://github.com/aldryn/aldryn-background-image

**Comment by oesah** [comment]
Wow, you're right. I knew that about style, but somehow class attribute never worked before, but now it does. Thanks for your feedback, keep up the great work!
