### ISSUE TITLE
Button/Link app Missing Template Error

### ISSUE THREAD

**Issue by johnmain** [django-cms/djangocms-bootstrap4#34]
Attempting to add a Button shows the following error:
![image](https://user-images.githubusercontent.com/2589334/38758464-0c3eec88-3f3f-11e8-9da4-64762074b627.png)

If I comment out the djangocms_bootstrap4.contrib.bootstrap4_link app I get the djangocms_link app with works correctly.

django-cms 3.5.2

**Comment by electroniceagle** [comment]
I also see this in django-cms 3.4.6 (LTS).  It is looking for:
admin/djangocms_icon/widgets/icon.html

**Comment by electroniceagle** [comment]
Taking a quick look could it be related to Django 1.11 changes?
https://docs.djangoproject.com/en/1.11/releases/1.11/#template-widget-incompatibilities-1-11

**Comment by electroniceagle** [comment]
Next time I'll read the error message before code diving.  You just need to install:
https://github.com/divio/djangocms-icon
and add  'djangocms_icon' to INSTALLED_APPS.

**Comment by johnmain** [comment]
That fixed the issue.

**Comment by johnmain** [comment]
Possibly need to Update the Install Instructions?  By default on a fresh install of DjangoCMS djangocms_icon is not included in my settings.py file.

**Comment by electroniceagle** [comment]
https://github.com/divio/djangocms-bootstrap4/pull/35
