### ISSUE TITLE
Error on carousel template 

### ISSUE THREAD

**Issue by mickaelmarin** [django-cms/djangocms-bootstrap4#47]
Hi,

The pypi version of djangocms_bootstrap4 have and error in default  template file "carousel.html"

` <ol class="carousel-indicators">
            {% for plugin in instance.child_plugin_instances %}
                <li data-target="#carousel-{{ instance.pk }}"
                    data-slide-to="{{ **forloop.counter** }}"   # replace by **forloop.counter0**
                    {% if forloop.first %} class="active"{% endif %}>
                </li>
            {% endfor %}
  </ol>
`
thanks

**Comment by vxsx** [comment]
Fixed in https://github.com/divio/djangocms-bootstrap4/commit/8d2663f04b23a5c39a2225426f299bd201df82c4

**Comment by vxsx** [comment]
Released in 1.1.0
