### ISSUE TITLE
Inline render creates an empty link in DjangoCMS CKEDITOR

### ISSUE THREAD

**Issue by joeljv91** [django-cms/djangocms-bootstrap4#53]
Hi

I tested this issue in django-cms (3.5.2) with djangocms-text-ckeditor (3.6.0) and every time I insert a bootstrap 4 link into Text plugin the preview render fails and in some cases when I press save the cms plugin it's not saved.

Steps to reproduce:
- Create text plugin and insert some lorem ipsum text.
- Select a word, click CMS Plugin and select Bootstrap4 Link/Button.
![selecting-text](https://user-images.githubusercontent.com/7562185/44039936-7e877b9e-9f1a-11e8-83f9-8bd80a25759d.png)
- In ckeditor you can see an empty text or cutted word.
![error-screenshot](https://user-images.githubusercontent.com/7562185/44039939-7fadf606-9f1a-11e8-8478-a79b0f46a18c.png)

I disabled djangocms_bootstrap4 link and tested with default djangocms_text and is working fine.

I'm the only one with this issue?

Thanks

**Comment by filwaitman** [comment]
Hi @joeljv91 !

I'm not being able to reproduce this issue. You can see a screencast of it working [here](https://drive.google.com/open?id=12GZkYxnxq4ODwl0SHVJvoGOPkcgCQALv).

Also I didn't hear this error for anyone else. Would you be able to rebuild your env and double check it still happens?

Also you can try it via djangocms-helper (as I did in my video) so you can see if this is a problem with the instalation or just a misconfiguration.
