### ISSUE TITLE
Code block renders as <pre> instead of <pre><code>

### ISSUE THREAD

**Issue by johnfraney** [django-cms/djangocms-bootstrap4#54]
Currently the code block WYSIWYG editor plugin renders a code block as [`<pre>`](https://github.com/divio/djangocms-bootstrap4/blob/master/djangocms_bootstrap4/contrib/bootstrap4_content/constants.py#L9) without a nested `<code>` element.

The [Bootstrap 4 documentation](http://getbootstrap.com/docs/4.1/content/code/#code-blocks) uses `<pre><code>` for multi-line code samples, and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#Notes) and some JS code syntax highlighting plugins (namely [Prism](https://prismjs.com/#features-full)) require that code be marked up this way.

Would it be possible to update this plugin to use this behaviour?

**Comment by filwaitman** [comment]
Fixed in version 1.1.2
