### ISSUE TITLE
English i18n messages are broken

### ISSUE THREAD

**Issue by alexbarcelo** [django-cms/djangocms-bootstrap4#58]
If I am not mistaken, just after installing the package one can find the following:

In file: `...venv/lib/python3.5/site-packages/djangocms_bootstrap4/locale/en/LC_MESSAGES/django.po`

```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
(...)
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"
```

That `Plural-Forms` entry is incomplete, and thus the system breaks. Because it happens in english, it breaks in all translated-including-english sites AFAICT.

I have just started doing internationalization, so I may be missing something. Once I fixed that line and executed the `compilemessages`, the site works as expected.

**Comment by filwaitman** [comment]
Fixed in version 1.1.2
