### ISSUE TITLE
Custom Link templates are selectable but do not get applied

### ISSUE THREAD

**Issue by masaruduy** [django-cms/djangocms-bootstrap4#73]
I created a template for links:
DJANGOCMS_LINK_TEMPLATES = [
    ('video_link', _('video_link')),
]

And although the option shows up in the plugin config, it doesn't get taken into consideration when selected.

![screen shot 2018-12-15 at 1 49 09 pm](https://user-images.githubusercontent.com/7341054/50046374-48d88f80-0070-11e9-852e-e9b5e0be5af6.png)

**Comment by Ballpin** [comment]
Hello,
They do get applied. I just tried it out. Your template needs to be in....
`my_cms/templates/djangocms_bootstrap4/link/default/link.html`

EDIT: Seems to work for default only

**Comment by FinalAngel** [comment]
@Ballpin the template path for that configuration would be:

``my_project/templates/djangocms_bootstrap4/link/video_link/link.html``

This should work in the latest version of this addon.

**Comment by masaruduy** [comment]
Works thanks!!
