### ISSUE TITLE
Carousel depends on Filer Image

### ISSUE THREAD

**Issue by jankopacek** [django-cms/djangocms-bootstrap4#77]
Carousel can have only one descendant slide due to bug in FilerImage - see:
https://github.com/divio/django-cms/issues/6198
With more slides it reports 'NoneType has no _inc_path'
Solution is probably switch Carousel model to django-picture.

**Comment by FinalAngel** [comment]
@jankopacek you are using cmsplugin-filer?

**Comment by jankopacek** [comment]
No -  https://github.com/divio/djangocms-bootstrap4/blob/master/djangocms_bootstrap4/contrib/bootstrap4_carousel/models.py#L15 is using filer

**Comment by FinalAngel** [comment]
@jankopacek I'm using the latest version of djangocms-bootstrap4 (1.3.1) and django Filer (1.4.1) and can add multiple items to the carousel without any issues. Are you using the latest versions as well?

I tested with Django 1.11 and 2.x.

**Comment by jankopacek** [comment]
I have django-filer==1.4.4, so maybe that is the problem will try.

**Comment by jankopacek** [comment]
My fault, please close. It is due to collation problem in treebeard referenced here. https://github.com/divio/django-cms/issues/5885
fixed like:
`ALTER TABLE public.cms_cmsplugin ALTER COLUMN path TYPE character varying(255) COLLATE pg_catalog."C";`
`ALTER TABLE public.cms_treenode ALTER COLUMN path TYPE character varying(255) COLLATE pg_catalog."C";`

**Comment by FinalAngel** [comment]
No problem, thanks for checking @jankopacek
