### ISSUE TITLE
grid column dialog: include margin top and margin bottom ui edits

### ISSUE THREAD

**Issue by woodz-** [django-cms/djangocms-bootstrap4#78]
You provide the margin left and margin right ui edits in the Column dialog. But it feels odd, when there are no edits for margin top and margin bottom. That would make it much more fluent, if one can specify all margins from within this dialog. One (like me) might think, he / she needs to add responsive spacing tags. But that is quite another thing and can lead to confusion.

Up to now one must know the secret of possibly extending the class attribute by the bootstrap's specific names to work around this. Is that your intention?

**Comment by FinalAngel** [comment]
Hello @woodz- , I assume you want to add the margin/padding class modifiers to it such as mt-1 or pl-3?

**Comment by woodz-** [comment]
Aloha @FinalAngel: yes indeed. Other samples are: `mb-3 mb-md-0`.
If you are going to provide even padding edits - so much the better! Up to now, just margin (left/right) is present, if nothing is magically hidden...

**Comment by FinalAngel** [comment]
@woodz- ahoi, the margin left and right classes on the grid column are actually [special types just for the grid](https://getbootstrap.com/docs/4.2/layout/grid/#margin-utilities).

We will not add all variants for the spacing utilities, for that please use attributes. Go to advanced settings, utilities and add the keyword "class" and choose any margin/padding combination to add that you'd wish :)
