### ISSUE TITLE
No field for alternative text in the image plugin

### ISSUE THREAD

**Issue by didierCH** [django-cms/djangocms-bootstrap4#79]
In the bootstrap3 images  plugin there is a field for the alt-tag (alternative text):

![grafik](https://user-images.githubusercontent.com/7381262/53173365-d348ec80-35e7-11e9-83b8-ca4190f5a7dd.png)

In the bootstrap4 image plugin this is replaced throug the figcaption element (Legend-Field in the plugin) and a figure element is created when filling that form field:
![grafik](https://user-images.githubusercontent.com/7381262/53173490-173bf180-35e8-11e9-9d37-42107b69435d.png)

I searched the web but didn't find some evidence that you should omit the alt-tag if you have a figcaption. The only thing I found is this: 
https://www.w3.org/TR/2014/REC-html5-20141028/embedded-content-0.html#when-a-text-alternative-is-not-available-at-the-time-of-publication

Could you briefly explain what considerations led to the old tag field being omitted?
I now that I can add an alt-tag through the attribute button but don't want to complicate things for my users.

**Comment by FinalAngel** [comment]
Hello @didierCH, the field was removed as the image itself uses the native alt settings from django Filer. [djangocms-picture uses that](https://github.com/divio/djangocms-picture/blob/7ceacd62af6ff87549b4da52b4813f0ba2dcd178/djangocms_picture/templates/djangocms_picture/default/picture.html#L17).

It is better to use the media manager (django-filer) to add metadata to the file itself. Sometimes a custom "alt" is required, for that please use the attributes field. The template takes that into consideration.

**Comment by didierCH** [comment]
Thank you. This makes sense. Didn't know about the alt setting in django filer.

**Comment by FinalAngel** [comment]
No worries 👍
