### ISSUE TITLE
original size image corousel 

### ISSUE THREAD

**Issue by mateoreyes** [django-cms/djangocms-bootstrap4#80]
I have a problem with the size of my carousel slide, it dont take the original size of the image.

How can I solve ?

![captura carousel](https://user-images.githubusercontent.com/25666016/53176868-b56e8e00-35cd-11e9-9bc6-0e0c7ad06137.png)

**Comment by FinalAngel** [comment]
Hello @mateoreyes the image just needs to be larger than the container or you need to select the correct ratio / thumbnail size. Are you using special settings?

**Comment by mateoreyes** [comment]
I want to change the size of the container, for example 70 x 70, I pass part of my files

python3.6/site-packages/djangocms_bootstrap4/contrib/bootstrap4_carousel/templates/djangocms_bootstrap4/carousel/default/carousel.html

    {% with 70 as width and 70 as height %}
        <div class="carousel-inner">
            {% for plugin in instance.child_plugin_instances %}
                {% render_plugin plugin %}
            {% endfor %}
        </div>
    {% endwith %}

 
python3.6/site-packages/djangocms_bootstrap4/contrib/bootstrap4_carousel

CAROUSEL_DEFAULT_SIZE = [70, 70]



the size of my image is 70 x 70 too

![idea](https://user-images.githubusercontent.com/25666016/53249731-a0f6c800-3697-11e9-8bee-78b783192b90.jpg)

**Comment by mateoreyes** [comment]
I could change the size of the container, for a particular image size.

But I can not make the container automatically adapt to the size of the image

**Comment by mateoreyes** [comment]
I have another problem, the container is not responsive
in this line I can not pass percentages

{% with 70 as width and 70 as height %}

**Comment by FinalAngel** [comment]
Percentages cannot be passed, if you want to implement responsive behaviours checkout the settings from [djangocms-picture](https://github.com/divio/djangocms-picture/blob/master/README.rst#configuration): ``DJANGOCMS_PICTURE_RESPONSIVE_IMAGES``

If you are using a 70x70 pixel image you need to make sure that the container (carousel) is also 70px large. Otherwise the CSS of the bootstrap 4 carousel will scale it up.
