### ISSUE TITLE
bootstrap4_link undefined icon prefix

### ISSUE THREAD

**Issue by Saeleas** [django-cms/djangocms-bootstrap4#83]
I found an issue when using the Link/Button plugin: when I try to set an icon (left or right) the iconpicker works correctly but the preview doesn't show the correct icon. From what I gathered the preview doesn't set a correct icon prefix (it sets it to undefined).

![bootstrap4_link-issue](https://user-images.githubusercontent.com/12183730/54812085-8c075780-4c8a-11e9-8e2b-0503d2146eaf.png)

This issue then breaks the plugin when it tries to render the icon after saving. In this case is the djangocms_icon module that crashes because it is trying to find the prefix (which is not set). The djangocms_icon plugin works correctly though.

I am using DjangoCMS 3.6 with Django 1.11.20 and djangocms-bootstrap4 1.3.1

**Comment by FinalAngel** [comment]
This has been fixed in 1.4.0 :=
