### ISSUE TITLE
Support for accordion?

### ISSUE THREAD

**Issue by ebugge** [django-cms/djangocms-bootstrap4#97]
aldryn-bootstrap3 had support for accordions. Will there be support for accordions (via card/collapse) in this project?

**Comment by FinalAngel** [comment]
Hello @ebugge . Bootstrap 4 removed the accordion functionality in favour of Collapse:
https://getbootstrap.com/docs/4.0/components/collapse/

This package provides that functionality. With [djangocms-modules](https://github.com/divio/djangocms-modules) you can easily create a copy & pastable accordion module :)

**Comment by maltebeckmann** [comment]
@FinalAngel Hi, it's great seeing this post. What's the difference between djangocms_modules and djangocms_bootstrap4? I am currently trying to figure out how to get my users to easily drag text plugins into a Collapse/Accordion.

**Comment by FinalAngel** [comment]
@maltebeckmann djangocms-bootstrap4 provides plugins for the various components the bootstrap 4 framework provides.

djangocms-modules allows a specific plugin structure to be stored as "new plugins" and later be re-used. It is independent from djangpcms-bootstrap4.
