### ISSUE TITLE
Not applying after using djangocms-installer

### ISSUE THREAD

**Issue by ghost** [django-cms/djangocms-bootstrap4#98]
The title speaks for itself. I created my project following the tutorial and the bootstrap styles don't apply. Did I miss something ?

**Comment by FinalAngel** [comment]
Hello @matthiasnuesch, the addon itself does not ship with the frontend css and javascript. It only provides the plugin functionality independent of the Bootstrap 4.x releases.

Please include them in your frontend. As in regards of djangocms-installer not adding the css styles automatically, you may raise the issue there :)
