### ISSUE TITLE
The column plugin editing modal is missing its icons and styles

### ISSUE THREAD

**Issue by viktor-yunenko** [django-cms/djangocms-bootstrap4#99]
I created an empty divio project using the default python3.6 & bootstrap 4 template, and installed djangocms-bootstrap4 using the addons tab.

Here's the link to the project - https://control.divio.com/control/5901/edit/77030/

![image](https://user-images.githubusercontent.com/36416236/70818638-e0380600-1ddc-11ea-8be1-027883576139.png)

In order to reset the cache I tried to open it with `cache disabled` in chrome dev tools, renamed the iframe `name` attribute and added one more GET parameter to its url - the issue seems to persists

**Comment by FinalAngel** [comment]
@victor-yunenko would https://github.com/divio/djangocms-bootstrap4/pull/100 fix the issue for you?

**Comment by viktor-yunenko** [comment]
Hi @FinalAngel, sorry for the delay. Not sure, hard to tell without a visual example. In short it used to look as following:

![image](https://user-images.githubusercontent.com/36416236/76410340-6cd07100-6398-11ea-9fee-ab0fd915f35d.png)

**Comment by FinalAngel** [comment]
@victor-yunenko the issue should have been fixed with #99. Though the new layout is not exactly the same as previously.
